version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "sleep 5; python manage.py migrate --noinput; python manage.py runserver 0.0.0.0:8000"
    command: bash -c "sleep 5; python manage.py migrate --noinput; gunicorn 'sftpserver.wsgi:application' --name sftp_admin --workers 1 -b 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level info"
    # environment:
    #   - STATIC_ROOT=/tmp/staticfiles

  sftp:
    extends: web
    command: bash -c "sleep 5; python manage.py run_sftpserver --storage-mode -k /run/secrets/ssh_host_key"
