version: '2'

volumes:
  pg_data:

services:
  # PostgreSQL database
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/postgres/data
    volumes:
      - pg_data:/postgres/data
    command: postgres -c max_connections=1000
  web:
    volumes:
      - ./sftpserver:/app/sftpserver
    ports:
      - "42037:8000"
  sftp:
    extends: web
    command: bash -c "sleep 5; python manage.py run_sftpserver --storage-mode -k /run/secrets/ssh_host_key"
    volumes:
      - ./test_host_key:/run/secrets/ssh_host_key
    environment:
      - DB_TYPE=postgres
      - DB_ADDR=db
      - DB_PORT=5432
    ports:
      - "22222:2222"
